browsing/urls.py
from django.conf.urls import url
from . import views

app_name = 'browsing'

urlpatterns = [
    url(r'^merge-objects/$', views.merge_objects, name='merge_objects'),
]

entities/urls.py
from django.conf.urls import url
from . import views

app_name = 'entities'

urlpatterns = [
    url(
        r'^person/$',
        views.PersonListView.as_view(),
        name='person_browse'
    ),
    url(
        r'^person/detail/(?P<pk>[0-9]+)$',
        views.PersonDetailView.as_view(),
        name='person_detail'
    ),
    url(
        r'^person/create/$',
        views.PersonCreate.as_view(),
        name='person_create'
    ),
    url(
        r'^person/edit/(?P<pk>[0-9]+)$',
        views.PersonUpdate.as_view(),
        name='person_edit'
    ),
    url(
        r'^person/delete/(?P<pk>[0-9]+)$',
        views.PersonDelete.as_view(),
        name='person_delete'),
    url(
        r'^personperson/$',
        views.PersonPersonListView.as_view(),
        name='personperson_browse'
    ),
    url(
        r'^personperson/detail/(?P<pk>[0-9]+)$',
        views.PersonPersonDetailView.as_view(),
        name='personperson_detail'
    ),
    url(
        r'^personperson/create/$',
        views.PersonPersonCreate.as_view(),
        name='personperson_create'
    ),
    url(
        r'^personperson/edit/(?P<pk>[0-9]+)$',
        views.PersonPersonUpdate.as_view(),
        name='personperson_edit'
    ),
    url(
        r'^personperson/delete/(?P<pk>[0-9]+)$',
        views.PersonPersonDelete.as_view(),
        name='personperson_delete'),
    url(
        r'^place/$',
        views.PlaceListView.as_view(),
        name='place_browse'
    ),
    url(
        r'^place/detail/(?P<pk>[0-9]+)$',
        views.PlaceDetailView.as_view(),
        name='place_detail'
    ),
    url(
        r'^place/create/$',
        views.PlaceCreate.as_view(),
        name='place_create'
    ),
    url(
        r'^place/edit/(?P<pk>[0-9]+)$',
        views.PlaceUpdate.as_view(),
        name='place_edit'
    ),
    url(
        r'^place/delete/(?P<pk>[0-9]+)$',
        views.PlaceDelete.as_view(),
        name='place_delete'),
    url(
        r'^institution/$',
        views.InstitutionListView.as_view(),
        name='institution_browse'
    ),
    url(
        r'^institution/detail/(?P<pk>[0-9]+)$',
        views.InstitutionDetailView.as_view(),
        name='institution_detail'
    ),
    url(
        r'^institution/create/$',
        views.InstitutionCreate.as_view(),
        name='institution_create'
    ),
    url(
        r'^institution/edit/(?P<pk>[0-9]+)$',
        views.InstitutionUpdate.as_view(),
        name='institution_edit'
    ),
    url(
        r'^institution/delete/(?P<pk>[0-9]+)$',
        views.InstitutionDelete.as_view(),
        name='institution_delete'),
]

invs/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from entities.apis_views import PlaceViewSet, GeoJsonViewSet
from vocabs import api_views

if 'bib' in settings.INSTALLED_APPS:
    from bib.api_views import ZotItemViewSet


router = routers.DefaultRouter()
router.register(r'geojson', GeoJsonViewSet, base_name='places')
router.register(r'metadata', api_views.MetadataViewSet)
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skoscollections', api_views.SkosCollectionViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'places', PlaceViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^arche/', include('arche.urls', namespace='arche')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^sparql/', include('sparql.urls', namespace='sparql')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^summaries/', include('summaries.urls', namespace='summaries')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^entities-ac/', include('entities.dal_urls', namespace='entities-ac')),
    url(r'^entities/', include('entities.urls', namespace='entities')),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^books-ac/', include('books.dal_urls', namespace='books-ac')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^', include('webpage.urls', namespace='webpage')),
]


handler404 = 'webpage.views.handler404'

entities/models.py
import re
import reversion
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from idprovider.models import IdProvider

from browsing.browsing_utils import model_to_dict
from vocabs.models import SkosConcept

from . utils import get_coordinates


@reversion.register()
class AlternativeName(IdProvider):
    name = models.CharField(
        max_length=250, blank=True, help_text="Alternative Name"
    )

    def get_next(self):
        next = AlternativeName.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = AlternativeName.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev.first().id
        return False

    def __str__(self):
        return "{}".format(self.name)


@reversion.register()
class Place(IdProvider):
    """Holds information about entities."""
    PLACE_TYPES = (
        ("city", "city"),
        ("country", "country")
    )
    name = models.CharField(
        max_length=250, blank=True, help_text="Normalized name"
    )
    alt_names = models.ManyToManyField(
        AlternativeName,
        max_length=250, blank=True,
        help_text="Alternative names",
        related_name="altname_of_place"
    )
    geonames_id = models.CharField(
        max_length=50, blank=True,
        help_text="GND-ID"
    )
    lat = models.DecimalField(
        max_digits=20, decimal_places=12,
        blank=True, null=True
    )
    lng = models.DecimalField(
        max_digits=20, decimal_places=12, blank=True, null=True
    )
    part_of = models.ForeignKey(
        "Place", null=True, blank=True,
        help_text="A place (country) this place is part of.",
        related_name="has_child",
        on_delete=models.SET_NULL
    )
    place_type = models.CharField(
        choices=PLACE_TYPES, null=True, blank=True, max_length=50
    )

    def get_geonames_url(self):
        if self.geonames_id.startswith('ht') and self.geonames_id.endswith('.html'):
            return self.geonames_id
        else:
            return "http://www.geonames.org/{}".format(self.geonames_id)

    def get_geonames_rdf(self):
        try:
            number = re.findall(r'\d+', str(self.geonames_id))[0]
            return number
        except Exception as e:
            return None

    def save(self, *args, **kwargs):
        if self.geonames_id:
            new_id = self.get_geonames_url()
            self.geonames_id = new_id
        if self.get_geonames_rdf() and not self.lat:
            coords = get_coordinates(self.get_geonames_rdf())
            if coords:
                self.lat = coords['lat']
                self.lng = coords['lng']
        super(Place, self).save(*args, **kwargs)

    @classmethod
    def get_listview_url(self):
        return reverse('entities:place_browse')

    @classmethod
    def get_createview_url(self):
        return reverse('entities:place_create')

    def get_absolute_url(self):
        return reverse('entities:place_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('entities:place_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('entities:place_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'entities:place_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'entities:place_detail',
                kwargs={'pk': prev.first().id}
            )
        return False

    def field_dict(self):
        return model_to_dict(self)

    def __str__(self):
        return "{}".format(self.name)


@reversion.register()
class Institution(IdProvider):
    legacy_id = models.CharField(max_length=300, blank=True)
    written_name = models.CharField(max_length=300, blank=True)
    authority_url = models.CharField(max_length=300, blank=True)
    alt_names = models.ManyToManyField(
        AlternativeName,
        max_length=250, blank=True,
        help_text="Alternative names",
        related_name="altname_of_inst"
    )
    abbreviation = models.CharField(max_length=300, blank=True)
    location = models.ForeignKey(
        Place, blank=True, null=True, on_delete=models.SET_NULL
    )
    parent_institution = models.ForeignKey(
        'Institution', blank=True, null=True, related_name='children_institutions',
        on_delete=models.SET_NULL
    )
    comment = models.TextField(blank=True)

    @classmethod
    def get_listview_url(self):
        return reverse('entities:institution_browse')

    @classmethod
    def get_createview_url(self):
        return reverse('entities:institution_create')

    def get_absolute_url(self):
        return reverse('entities:institution_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('entities:institution_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('entities:institution_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id)
        if next:
            return reverse(
                'entities:institution_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):
        prev = self.__class__.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return reverse(
                'entities:institution_detail',
                kwargs={'pk': prev.first().id}
            )
        return False

    def field_dict(self):
        return model_to_dict(self)

    def __str__(self):
        return "{}".format(self.written_name)


@reversion.register()
class Person(IdProvider):
    legacy_id = models.CharField(max_length=300, blank=True)
    written_name = models.CharField(
        max_length=300, blank=True,
        verbose_name="Umfassende Pesonenbezeichnung"
    )
    written_name_leven = models.CharField(max_length=254, blank=True)
    forename = models.CharField(
        max_length=300, blank=True,
        verbose_name="Vorname"
    )
    gender = models.CharField(
        max_length=300, blank=True,
        verbose_name="Geschlecht"
    )
    name = models.CharField(
        max_length=300, blank=True,
        verbose_name="Nachname"
    )
    house_name = models.CharField(
        max_length=300, blank=True,
        verbose_name="Hausname"
    )
    alt_names = models.ManyToManyField(
        AlternativeName,
        max_length=250, blank=True,
        help_text="Alternative names",
        related_name="altname_of_persons"
    )
    profession = models.ManyToManyField(
        SkosConcept, blank=True,
        verbose_name="Beruf(e)",
        related_name="is_profession_of"
    )
    belongs_to_place = models.ManyToManyField(
        Place, blank=True,
        related_name="living_place_for",
        verbose_name="Wohn- und Wirkungsort(e)",
    )
    place_of_birth = models.ForeignKey(
        Place, blank=True, null=True, related_name="is_birthplace",
        verbose_name="Geburtsort",
        on_delete=models.SET_NULL
    )
    place_of_death = models.ForeignKey(
        Place, blank=True, null=True, related_name="is_deathplace",
        verbose_name="Sterbeort",
        on_delete=models.SET_NULL
    )
    date_of_birth = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True,
        verbose_name="Geburtsdatum",
        help_text="YYYY-MM-DD"
    )
    date_of_death = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True,
        verbose_name="Sterbedatum",
        help_text="YYYY-MM-DD"
    )
    belongs_to_institution = models.ForeignKey(
        Institution, blank=True, null=True, related_name="has_member",
        on_delete=models.SET_NULL
    )
    comment = models.TextField(blank=True)
    is_main = models.BooleanField(
        blank=True, null=True,
        verbose_name="Name (Erklärung aus Verfachbuch)",
        help_text="Identifizierbare Personen, die im Eintrag erwähnt werden."
    )
    is_adm = models.BooleanField(
        blank=True, null=True,
        verbose_name="Beteiligte (administrative) Personen",
        help_text="Beteiligte Personen (Beamte, Gerichtsverpflichtete, Zeugen, ...).",
    )
    is_related = models.BooleanField(
        blank=True, null=True,
        verbose_name="Beteiligte (nicht-administrative) Personen",
        help_text="Beteiligte Personen (Erbsinteressenten, Gerhaben, Anweiser,\
        Verkäufer, Verpächter, Käufer, Pächter, ...)."
    )
    is_other = models.BooleanField(
        blank=True, null=True,
        verbose_name="Sonstig genannte Personen",
        help_text="Sonstig genannte Personen.",
    )

    class Meta:
        ordering = ['id']

    @classmethod
    def get_listview_url(self):
        return reverse('entities:person_browse')

    @classmethod
    def get_createview_url(self):
        return reverse('entities:person_create')

    def get_absolute_url(self):
        return reverse('entities:person_detail', kwargs={'pk': self.id})

    def get_absolute_url(self):
        return reverse('entities:person_detail', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('entities:person_delete', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('entities:person_edit', kwargs={'pk': self.id})

    def get_next(self):
        next = self.__class__.objects.filter(id__gt=self.id).order_by('id')
        if next:
            return reverse(
                'entities:person_detail',
                kwargs={'pk': next.first().id}
            )
        return False

    def get_prev(self):

entities/templates/entities/alternativename_list.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}List of Alternative Names{% endblock %}

{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">list all names</div>
  <div class="panel-body">
      <ul>
          {% for x in object_list %}
          <li>{{ x }}</li>
          {% endfor %}
      </ul>
  </div>
</div>



{% endblock %}

entities/templates/entities/alternativenames_create.html
{% extends "webpage/base.html" %}
{% block Title %} Create/Modify Alternative Name {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Create/Edit Alternative Name</h1>
    </div>
    <div class="panel-body">
         {% crispy form %}
    </div>
</div>
</div>
{% endblock content %}

entities/templates/entities/alternativenames_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to
include 'autocomplete_light/static.html
-->
<!--leafletjs -->
<link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
<script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
<style>
#map { height: 500px; }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="panel panel-default procustom-panel-create">
        <div class="panel-heading procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                    <h2>
                        <a href="{% url 'entities:alternativename_detail' pk=object.get_prev %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true" title="previous"></span></a>
                    </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>alternative name:</small> {{ object.name }}
                        {% if user.is_authenticated %}
                        <small><a href="{% url 'entities:alternativename_edit' pk=object.id %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></span>
                        </a>
                    </small>
                    {% endif %}
                </h1>
            </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'entities:alternativename_detail' pk=object.get_next %}" style="float:right"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true" title="next"></span></a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="panel-body">
                <legend>About</legend>
                <table class="table table-bordered table-hover">
                <tr>
                    <th>related places</th>
                    <td>
                        <ul>
                            {% for x in object.related_places.all %}
                            {% if x.id %}
                            <li><a href="{% url 'entities:place_detail' pk=x.id %}">{{ x }}</a></li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>
        {% if user.is_authenticated %}
            <a class="btn btn-danger" href="{% url 'entities:alternativename_delete' pk=object.id %}">delete</a>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

entities/templates/entities/edit_places.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to
    include 'autocomplete_light/static.html
-->
<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

{% if object %}
<div class="row">
    <div class="col-md-4">
{% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                  <h3>{%if object %} Edit {% else %} Create {% endif %}</h3>
            </div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    {% if object %}
                    <a class="btn btn-default btn-block" target="_blank">Check<span id="currentID"></span></a>
                    {% endif %}
                    <input class="btn btn-primary btn-block" type="submit" value="Save" />
                    {% if object %}
                    <a class ="btn btn-danger btn-sm" href="{% url 'entities:place_delete' pk=object.id %}">delete</a>
                    {% endif %}
                </form>
           </div>
       </div>
{% if object %}
   </div>
    <div class ="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <form class="form-group">
                    <select class="form-control" id="geonamesSELECT">
                            {% if object.geonames_id or object.lat %}
                                <option id="geonamesOption" value="{{ object.name }}_{{ object.lat }}_{{ object.lng }}_{{ object.geonames_id }}">DB-Entry | {{ object.name }} | {{ object.lat }} | {{ object.lng }} | {{ object.geonames_id }}</option>
                            {% endif %}
                            {% for dict in responseJSON %}
                            <option id="geonamesOption" value="{{ dict.countryName }}_{{ dict.name }}_{{ dict.lat }}_{{ dict.lng }}_{{ dict.geonameId }}"> {{ dict.countryName }} | {{ dict.name }} | {{ dict.lat }} | {{ dict.lng }} | {{ dict.geonameId }}</option>
                            {% endfor %}
                        </select>
                    </form>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>
{% endif %}


<script type="text/javascript">
    $(document).ready(function(){
        $("#id_alias_name-autocomplete").after('<button id="add_aliasName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus" /></button>');
    });
    $(document).ready(function(){
        $("#id_alternative_name-autocomplete").after('<button id="add_alternativeName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus"/></button>');
    });
</script>
{% if object %}
<script type="text/javascript">
    $( document ).ready(function() {
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 10);

       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
        .bindPopup(placeName)
        .openPopup();
        });
</script>


<script type="text/javascript">
    $( document ).ready(function(){
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
        var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

    });
</script>

<script type="text/javascript">
    $("#geonamesSELECT").change(function(){
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
       var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 15);
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
       var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
            .bindPopup(placeName)
            .openPopup();
});
</script>
{% endif %}
{% endblock %}

entities/templates/entities/institution_create.html
{% extends "webpage/base.html" %}
{% block Title %} Create/Modify Institution {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Create/Edit Institution</h1>
    </div>
    <div class="panel-body">
         {% crispy form %}
    </div>
</div>
</div>
{% endblock content %}

entities/templates/entities/list_places.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}List of Places{% endblock %}

{% block scriptHeader %}<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}
{% block content %}
{% if object_list %}
  <div class="row">
    <div class="col-md-4">
        <div class="panel panel-default panel-fixed" >
            <div class="panel-heading" style="text-align:center;">
                <h3>Places</h3>
          {% if user.is_authenticated %}
            <a href="{% url 'entities:place_create' %}">(add another Place)</a>
          {% endif %}
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>GeoNames</th>
                        </th>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr>
                            <td>
                {% if user.is_authenticated %}
                  <a href="{% url 'entities:place_edit' pk=object.id %}">{{ object }} (edit)</a>
                  {% else %}
                  {{ object }}
                {% endif %}
              </td>
                            <td>{{ object.geonames_id }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading" style="text-align:center;">
                <h3>Geovisualisation</h3>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $( document ).ready(function() {
         $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");

        var map = L.map('map').setView([48.69096, 9.14062], 5);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);

        {% for object in object_list %}
        {% if object.lat %}
        L.marker([{{ object.lat }}, {{ object.lng }}])
        .addTo(map)
        .bindPopup("<h1>{{ object.name }}</h1> <table class='table table-striped'> <tr> <td>Name: </td> <td>{{ object.name }}</td> </tr> </table>");
        {% endif %}
        {% endfor %}
        });
</script>
{% else %}

  {% if user.is_authenticated %}
  <div class="panel panel-default">
        <div class="panel-heading">
            <h1>Places</h1>
            <div>
                <a class="btn btn-primary" href="{% url 'entities:place_create' %}" role="button">
                    crate a new location/place
                </a>
            </div>
            <br />
        </div>
        <div class="panel-body">
        </div>
    </div>

  {% endif %}
{% endif %}
{% endblock %}

entities/templates/entities/person_create.html
{% extends "webpage/base.html" %}
{% block Title %} Create/Modify Person {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1>Create/Edit Person</h1>
        </div>
        <div class="panel-body">
             {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}