invs/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from entities.apis_views import PlaceViewSet, GeoJsonViewSet
from vocabs import api_views

if 'bib' in settings.INSTALLED_APPS:
    from bib.api_views import ZotItemViewSet


router = routers.DefaultRouter()
router.register(r'geojson', GeoJsonViewSet, base_name='places')
router.register(r'metadata', api_views.MetadataViewSet)
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skoscollections', api_views.SkosCollectionViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'places', PlaceViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^arche/', include('arche.urls', namespace='arche')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^sparql/', include('sparql.urls', namespace='sparql')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^summaries/', include('summaries.urls', namespace='summaries')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^entities-ac/', include('entities.dal_urls', namespace='entities-ac')),
    url(r'^entities/', include('entities.urls', namespace='entities')),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^books-ac/', include('books.dal_urls', namespace='books-ac')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^', include('webpage.urls', namespace='webpage')),
]


handler404 = 'webpage.views.handler404'

webpage/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

app_name = 'webpage'

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^favicon\.ico$', favicon_view),
    url(r'^imprint', views.ImprintView.as_view(), name="imprint"),
    url(r'^$', views.GenericWebpageView.as_view(), name="start"),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^project-info/$', views.project_info, name='project_info'),
    url(r'^(?P<template>[\w-]+)/$', views.GenericWebpageView.as_view(), name='staticpage'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'login'))

webpage/views.py
from copy import deepcopy

import requests

from django.conf import settings
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import RequestContext, loader
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout

from . forms import form_user_login
from . metadata import PROJECT_METADATA as PM


def get_imprint_url():
    try:
        base_url = settings.ACDH_IMPRINT_URL
    except AttributeError:
        base_url = "https://provide-an-acdh-imprint-url/"
    try:
        redmine_id = settings.REDMINE_ID
    except AttributeError:
        redmine_id = "go-register-a-redmine-service-issue"
    return "{}{}".format(base_url, redmine_id)


class ImprintView(TemplateView):
    template_name = 'webpage/imprint.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imprint_url = get_imprint_url()
        r = requests.get(get_imprint_url())

        if r.status_code == 200:
            context['imprint_body'] = "{}".format(r.text)
        else:
            context['imprint_body'] = """
            On of our services is currently not available. Please try it later or write an email to
            acdh@oeaw.ac.at; if you are service provide, make sure that you provided ACDH_IMPRINT_URL and REDMINE_ID
            """
        return context


class GenericWebpageView(TemplateView):
    template_name = 'webpage/index.html'

    def get_context_data(self, **kwargs):
        context = super(GenericWebpageView, self).get_context_data(**kwargs)
        context['apps'] = settings.INSTALLED_APPS
        return context

    def get_template_names(self):
        template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        try:
            loader.select_template([template_name])
            template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        except:
            template_name = "webpage/index.html"
        return [template_name]


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render_to_response('webpage/user_logout.html')


def handler404(request, exception):
    return render(request, 'webpage/404-error.html', locals())


def project_info(request):

    """
    returns a dict providing metadata about the current project
    """

    info_dict = deepcopy(PM)

    if request.user.is_authenticated:
        pass
    else:
        del info_dict['matomo_id']
        del info_dict['matomo_url']
    info_dict['base_tech'] = 'django'
    info_dict['framework'] = 'djangobaseproject'
    return JsonResponse(info_dict)

webpage/templates/webpage/404-error.html
{% extends "webpage/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container">
<div style="text-align: center;">
    
    <h2>We're sorry, the page you requested cannot be found.</h2>
    <p style="text-align: center">The page you're trying to access may not exist anymore or may have been moved. Try accessing it again from our site's homepage. Please also make sure that your spelling is correct.</p>
    <p style="text-align: center">If the problem persists, please report it as an issue <a href="https://github.com/acdh-oeaw/invs/issues">here</a>. Thank you!</p>

</div>
</div>
{% endblock %}

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block title %} About {% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">{% projects_metadata 'title' %}</h1>
        </div>
        <div class="card-body">
            <div>
                <p>
                    {% projects_metadata 'description' %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webpage/templates/webpage/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load webpage_extras %}
{% load browsing_extras %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% projects_metadata 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metaDescription %}
        <meta name="description" content="{{ metadata.description }}">
        <meta name="author" content="{{ metadata.author }}">
    {% endblock %}
    <!-- favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'webpage/img/favicon/apple-touch-icon.png' %}"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'webpage/img/favicon/favicon-32x32.png' %}"/>
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'webpage/img/favicon/favicon-16x16.png' %}"/>
        <link rel="manifest" href="{% static 'webpage/img/favicon/manifest.json' %}"/>
        <link rel="mask-icon" href="{% static 'webpage/img/favicon/safari-pinned-tab.svg' %}" color="#00aba9"/>
        <meta name="theme-color" content="#ffffff"/>
    <!--favicons end -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'webpage/css/fundament.css' %}" rel="stylesheet"/>
    <!-- <link rel="stylesheet" href="{% static 'webpage/css/fundament_new.css' %}" rel="stylesheet"/> -->
    <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}" />
    <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
    <script type="text/javascript">
        window.cookieconsent_options = {
            "message":"This website uses cookies to ensure you get the best experience on our website",
            "dismiss":"Got it!",
            "learnMore":"More info",
            "link":"{% projects_metadata 'imprint' %}",
            "theme":"dark-bottom"};
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
    <!-- End Cookie Consent plugin -->
    <!-- Matomo -->
      <script type="text/javascript">
        var _paq = _paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
          var u="{% projects_metadata 'matomo_url' %}";
          _paq.push(['setTrackerUrl', u+'piwik.php']);
          _paq.push(['setSiteId', '{% projects_metadata "matomo_id" %}']);
          var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
          g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
      </script>
    <!-- End Matomo Code -->
    {% block scriptHeader %}
    {% endblock %}
</head>
<body role="document" class="contained fixed-nav">
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top bg-white box-shadow">
            <a class="navbar-brand" href="/">
                <img src="{% static 'webpage/img/project_logo.png' %}" alt="Rita" title="Reading in the Alps, logo (c) by Sandra Lehecka"/>
            </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About
                                <span class="caret"/>
                            </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'webpage:staticpage' template='about' %}">About project</a>
                                    <a class="dropdown-item" href="{% url 'webpage:staticpage' template='imprint' %}">Imprint | Impressum</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                {% if user.is_authenticated %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Curate and Browse the Data
                                <span class="caret"/>
                                </a>
                                {% else %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse the Data
                                <span class="caret"/>
                                </a>
                                {% endif %}
                                <div class="dropdown-menu">
                                    {% nav_menu app='summaries' as links %}
                                    {% for x in links %}

                                            <a class="dropdown-item" href="{{ x.link}}">{{ x.name }}</a>

                                    {% endfor %}
                                    {% nav_menu app='entities' as links %}
                                    {% for x in links %}

                                            <a class="dropdown-item" href="{{ x.link}}">{{ x.name }}</a>

                                    {% endfor %}
                                    {% nav_menu app='books' as links %}
                                    {% for x in links %}

                                            <a class="dropdown-item" href="{{ x.link}}">{{ x.name }}</a>

                                    {% endfor %}

                                </div>
                            </li>
                    {% if 'vocabs' in APPS %}
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vocabs Curation
                            <span class="caret"/>
                            </a>
                                <div class="dropdown-menu">
                                    {% nav_menu app='vocabs' as links %}
                                    {% for x in links %}
                                        <a class="dropdown-item" href="{{ x.link }}">{{ x.name }}</a>
                                    {% endfor %}
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'api-root' %}">Export SKOS (API)</a>
                                </div>
                            </li>
                        {% endif %}
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown ml-auto">
                        <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user.get_username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="nav-link" href="{% url 'webpage:user_logout' %}">Log-Out</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown ml-auto">
                        <a class="nav-link" href="{% url 'webpage:user_login' %}">
                        <i class="fas fa-sign-in-alt"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <div class="navbar-icons">
                    <a href="{% projects_metadata 'github' %}" target="_blank" rel="noopener">
                        <i class="fab fa-github"></i>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <section class="main-content">
        {% if DEV_VERSION %}
        <div class="alert alert-danger" role="alert">
            This is a the DEVELOPMENT instance. Click <a href="#">here</a> for the Production version
        </div>
        {% endif %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </section>
    <footer class="main-footer">
        <div class="container">
            <div class="footer-wrapper">
                <div class="footer-sep">
                    <i class="far fa-comment"></i> CONTACT
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <a href="https://www.oeaw.ac.at/acdh/acdh-home/" target="_blank" rel="noopener" aria-label="ACDH">
                            <img src="https://shared.acdh.oeaw.ac.at/acdh-common-assets/images/acdh_logo.svg" alt="ACDH" title="Austrian Centre for Digital Humanities"/>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="https://pf.fwf.ac.at/de/wissenschaft-konkret/project-finder?search[what]=P+29329" target="_blank" rel="noopener" aria-label="FWF P 29329">
                            <img src="{% static 'webpage/img/fwf.gif' %}" alt="FWF" title="FWF funded Project P 29329"/>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="https://www.tirol.gv.at/bildung/tiroler-wissenschaftsfoerderung/" target="_blank" rel="noopener" aria-label="Tiroler Wissenschaftförderung">
                            <img src="{% static 'webpage/img/twf_logo.png' %}" alt="TWF" title="Tiroler Wissenschaftförderung"/>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="https://www.uibk.ac.at/" target="_blank" rel="noopener" aria-label="UIBK">
                            <img src="{% static 'webpage/img/uibklogo.png' %}" alt="UIBK" title="University of Innsbruck"/>
                        </a>
                    </div>
                </div>
            </div>
        </div>
            </div>
            <div class="footer-imprint-bar">
                <a href="{% projects_metadata 'imprint' %}">Impressum/Imprint</a>

                {% if user.is_authenticated %}
                    {% if DB_NAME %}
                        <div class="footer-imprint-bar">
                            <small>{{ DB_NAME }}</small>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </footer>
        {% block scripts %}
        <script src="https://fundament.acdh.oeaw.ac.at/dist/fundament/vendor/js/fontawesome-all.min.js"></script>
        <script src="https://fundament.acdh.oeaw.ac.at/dist/fundament/js/fundament.min.js"></script>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css" />
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
        <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $.apScrollTop({'onInit': function(evt) {console.log('apScrollTop: init');}});
            });
        </script>
        {% endblock %}
        {% block scripts2 %}
        {% endblock scripts2 %}
        <noscript>
            <img src="//piwik.apollo.arz.oeaw.ac.at/piwik.php?idsite=48" style="border:0;" alt=""/>
        </noscript>
        </body>
        </html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong>{{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn" type="submit" value="No, bring me back" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

webpage/templates/webpage/imprint.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block title %} Imprint {% endblock %}
{% block content %}
<div class="container">
<div class="card imprint">
<div class="card-body">
    {{ imprint_body|safe }}
</div>
</div>
</div>
{% endblock %}

webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load stats_extras %}
{% load webpage_extras %}
{% block content %}

        <div class="jumbotron" style="background-image: url({% static 'webpage/img/project_background.jpg' %}) ">
            <div class="container">
                <h1 style="text-align:center; color: #111;">{% projects_metadata 'title' %}</h1>
                <h3 style="text-align:center; color: #111;">{% projects_metadata 'subtitle' %}</h3>
                <h5 style="text-align:center; color: #111;">{% projects_metadata 'description' %}</h5>
            </div>
        </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h5 class="row-heading pb-2 mb-3 border-bottom"><i class="fas fa-paste"></i> Data-Count</h5>
            </div>

            <hr />
            {% create_object_count app='summaries' as models %}
            {% for x in models %}
                <div class="col-md-6  text-center">
                    <div class="card flex-md-row mb-4 box-shadow">
                        <div class="card-body">
                            <h4 class="mb-0">{{x.name}}</h4>
                            <h4 class="count">{{ x.count }}</h4>
                            {% if x.link %}
                                <a class="btn btn-main btn-outline-primary btn-sm" href="{{ x.link }}" role="button">View Details</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <br />
    {% if form.errors %}
        <p style="color:red;">Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}
    {% load crispy_forms_tags %}
    {% crispy form form.helper %}
</div>
{% endblock %}

webpage/templates/webpage/user_logout.html
{% extends "webpage/base.html" %}
{% block title %}logout{% endblock %}
{% block content %}
<div class="jumbotron container">
    <h1>Sayōnara!</h1>
    <p>You've signed out</p>
</div>
{% endblock content %}