arche/urls.py
from django.conf.urls import url
from . import views

app_name = 'arche'

urlpatterns = [
    url(r'^projects/$', views.ProjectListView.as_view(), name='browse_projects'),
    url(r'^project/detail/(?P<pk>[0-9]+)$', views.ProjectDetailView.as_view(),
        name='project_detail'),
    url(r'^project/create/$', views.ProjectCreate.as_view(),
        name='project_create'),
    url(r'^project/edit/(?P<pk>[0-9]+)$', views.ProjectUpdate.as_view(),
        name='project_edit'),
    url(r'^project/delete/(?P<pk>[0-9]+)$', views.ProjectDelete.as_view(),
        name='project_delete'),
    url(r'projects-rdf/$', views.ProjectRDFView.as_view(), name='rdf_projects'),
    url(r'^collections/$', views.CollectionListView.as_view(), name='browse_collections'),
    url(r'^collection/detail/(?P<pk>[0-9]+)$', views.CollectionDetailView.as_view(),
        name='collection_detail'),
    url(r'^collection/create/$', views.CollectionCreate.as_view(),
        name='collection_create'),
    url(r'^collection/edit/(?P<pk>[0-9]+)$', views.CollectionUpdate.as_view(),
        name='collection_edit'),
    url(r'^collection/delete/(?P<pk>[0-9]+)$', views.CollectionDelete.as_view(),
        name='collection_delete'),
    url(r'collections-rdf/$', views.CollectionRDFView.as_view(), name='rdf_collections'),
    url(r'^resources/$', views.ResourceListView.as_view(), name='browse_resources'),
    url(
        r'^resources-inherit/$', views.ResourceInheritProperties.as_view(),
        name='resource_inherit'
    ),
    url(r'^resource/detail/(?P<pk>[0-9]+)$', views.ResourceDetailView.as_view(),
        name='resource_detail'),
    url(r'^resource/create/$', views.ResourceCreate.as_view(),
        name='resource_create'),
    url(r'^resource/edit/(?P<pk>[0-9]+)$', views.ResourceUpdate.as_view(),
        name='resource_edit'),
    url(r'^resource/delete/(?P<pk>[0-9]+)$', views.ResourceDelete.as_view(),
        name='resource_delete'),
    url(r'^resources-copy/$', views.copy_view, name='resource_copy'),
    url(r'resources-rdf/$', views.ResourceRDFView.as_view(), name='rdf_resources'),
]

invs/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from entities.apis_views import PlaceViewSet, GeoJsonViewSet
from vocabs import api_views

if 'bib' in settings.INSTALLED_APPS:
    from bib.api_views import ZotItemViewSet


router = routers.DefaultRouter()
router.register(r'geojson', GeoJsonViewSet, base_name='places')
router.register(r'metadata', api_views.MetadataViewSet)
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skoscollections', api_views.SkosCollectionViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'places', PlaceViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^arche/', include('arche.urls', namespace='arche')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^sparql/', include('sparql.urls', namespace='sparql')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^summaries/', include('summaries.urls', namespace='summaries')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^entities-ac/', include('entities.dal_urls', namespace='entities-ac')),
    url(r'^entities/', include('entities.urls', namespace='entities')),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^books-ac/', include('books.dal_urls', namespace='books-ac')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^', include('webpage.urls', namespace='webpage')),
]


handler404 = 'webpage.views.handler404'

arche/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.bootstrap import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, Div, MultiField, HTML
from .models import Project, Collection, Resource


class ProjectFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ProjectFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'has_title',
                'description',
                css_id="basic_search_fields"
                ),
############# Uncomment accordion if there are advanced search options ############
            # Accordion(
            #     AccordionGroup(
            #         'Advanced search',
            #         css_id="more"
            #         ),
            #     )
            )


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class CollectionFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(CollectionFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'has_title',
                'description',
                css_id="basic_search_fields"
                ),
############# Uncomment accordion if there are advanced search options ############
            # Accordion(
            #     AccordionGroup(
            #         'Advanced search',
            #         css_id="more"
            #         ),
            #     )
            )


class CollectionForm(forms.ModelForm):
    class Meta:
        model = Collection
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(CollectionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class ResourceFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ResourceFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.helper.form_tag = False
        self.add_input(Submit('Filter', 'Search'))
        self.layout = Layout(
            Fieldset(
                'Basic search options',
                'has_title',
                'description',
                'part_of',
                css_id="basic_search_fields"
                ),
############# Uncomment accordion if there are advanced search options ############
            # Accordion(
            #     AccordionGroup(
            #         'Advanced search',
            #         css_id="more"
            #         ),
            #     )
            )


class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resource
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ResourceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)

arche/views.py
import time
import datetime
import rdflib
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from django_tables2 import SingleTableView, RequestConfig
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from .models import Project, Collection, Resource
from .forms import *
from .filters import *
from .tables import *
from .serializer_arche import *
from browsing.browsing_utils import GenericListView, BaseCreateView, BaseUpdateView


def copy_view(request):
    """View looks for get-params with: name of application, of model and id\
    of instance of model which should be copied"""

    class_name = request.GET.get('class-name', '')
    object_id = request.GET.get('id', '')
    app_name = request.GET.get('app-name', 'arche')
    if object_id and class_name:
        class_name = class_name.lower()
        app_name = app_name.lower()
        try:
            object_id = int(object_id)
        except ValueError:
            html = "<html><body>Wrong format of id-param</body></html>"
            return HttpResponse(html)
        try:
            cont_type = ContentType.objects.get(app_label=app_name, model=class_name)
        except ObjectDoesNotExist:
            html = "<html><body>Wrong format of class_name-param</body></html>"
            return HttpResponse(html)
        try:
            current_object = cont_type.get_object_for_this_type(id=object_id)
        except ObjectDoesNotExist:
            html = "<html><body>Resource matching query does not exist.</body></html>"
            return HttpResponse(html)
        new_object = current_object.copy_instance()
        try:
            return redirect(new_object)
        except:
            html = """<html>
            <body>The object was saved but somehting is wrong with the redirect.
            Please check if the Class of the instance you try to copy has a
            get_absolute_url method defined</body>
            </html>"""
            return HttpResponse(html)
    else:
        html = """<html>
        <body>Either id or class-name params are missing</body>
        </html>"""
        return HttpResponse(html)


class ProjectListView(GenericListView):
    model = Project
    table_class = ProjectTable
    filter_class = ProjectListFilter
    formhelper_class = ProjectFilterFormHelper
    init_columns = [[
        'id',
        'has_title',
    ]]


class ProjectRDFView(GenericListView):
    model = Project
    table_class = ProjectTable
    template_name = None
    filter_class = ProjectListFilter
    formhelper_class = ProjectFilterFormHelper

    def render_to_response(self, context):
        timestamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
        response = HttpResponse(content_type='application/xml; charset=utf-8')
        filename = "{}_{}".format(self.model.__name__, timestamp)
        response['Content-Disposition'] = 'attachment; filename="{}.rdf"'.format(filename)
        g = project_to_arche(self.get_queryset())
        get_format = self.request.GET.get('format', default='n3')
        result = g.serialize(destination=response, format=get_format)
        return response


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'arche/project_detail.html'


class ProjectCreate(BaseCreateView):

    model = Project
    form_class = ProjectForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectCreate, self).dispatch(*args, **kwargs)


class ProjectUpdate(BaseUpdateView):

    model = Project
    form_class = ProjectForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectUpdate, self).dispatch(*args, **kwargs)


class ProjectDelete(DeleteView):
    model = Project
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('arche:browse_projects')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectDelete, self).dispatch(*args, **kwargs)


class CollectionListView(GenericListView):
    model = Collection
    table_class = CollectionTable
    filter_class = CollectionListFilter
    formhelper_class = CollectionFilterFormHelper
    init_columns = [
        'id',
        'has_title'
    ]


class CollectionRDFView(GenericListView):
    model = Collection
    table_class = CollectionTable
    template_name = None
    filter_class = CollectionListFilter
    formhelper_class = CollectionFilterFormHelper

    def render_to_response(self, context):
        timestamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
        response = HttpResponse(content_type='application/xml; charset=utf-8')
        filename = "{}_{}".format(self.model.__name__, timestamp)
        response['Content-Disposition'] = 'attachment; filename="{}.rdf"'.format(filename)
        g = collection_to_arche(self.get_queryset())
        get_format = self.request.GET.get('format', default='n3')
        result = g.serialize(destination=response, format=get_format)
        return response


class CollectionDetailView(DetailView):
    model = Collection
    template_name = 'arche/collection_detail.html'


class CollectionCreate(BaseCreateView):

    model = Collection
    form_class = CollectionForm
    # template_name = 'arche/collection_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CollectionCreate, self).dispatch(*args, **kwargs)


class CollectionUpdate(BaseUpdateView):

    model = Collection
    form_class = CollectionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CollectionUpdate, self).dispatch(*args, **kwargs)


class CollectionDelete(DeleteView):
    model = Collection
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('arche:browse_collections')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CollectionDelete, self).dispatch(*args, **kwargs)


class ResourceListView(GenericListView):
    model = Resource
    table_class = ResourceTable
    filter_class = ResourceListFilter
    formhelper_class = ResourceFilterFormHelper
    init_columns = [
        'id',
        'has_title',
    ]


class ResourceDetailView(DetailView):
    model = Resource
    template_name = 'arche/resource_detail.html'


class ResourceCreate(BaseCreateView):

    model = Resource
    form_class = ResourceForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ResourceCreate, self).dispatch(*args, **kwargs)


class ResourceUpdate(BaseUpdateView):

    model = Resource
    form_class = ResourceForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ResourceUpdate, self).dispatch(*args, **kwargs)


class ResourceDelete(DeleteView):
    model = Resource
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('arche:browse_resources')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ResourceDelete, self).dispatch(*args, **kwargs)


class ResourceInheritProperties(ResourceListView):
    template_name = 'arche/resource_browse.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ResourceInheritProperties, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ResourceInheritProperties, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        new_props = []
        for x in self.get_queryset():
            new = x.inherit_properties()
        new_props.append(new)
        context['updat_report'] = new_props
        return context


class ResourceRDFView(GenericListView):
    model = Resource
    table_class = ResourceTable
    template_name = None
    filter_class = ResourceListFilter
    formhelper_class = ResourceFilterFormHelper

    def render_to_response(self, context):
        timestamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
        response = HttpResponse(content_type='application/xml; charset=utf-8')
        filename = "{}_{}".format(self.model.__name__, timestamp)
        response['Content-Disposition'] = 'attachment; filename="{}.rdf"'.format(filename)
        g = resource_to_arche(self.get_queryset())
        get_format = self.request.GET.get('format', default='n3')
        result = g.serialize(destination=response, format=get_format)
        return response

arche/templates/arche/collection_detail.html
{% extends "arche/repo_object_base.html" %}
{% load staticfiles %}
{% load arche_filters %}
{% block title %}Collection{% endblock %}
{% block repo_header %}


    <div class="card-header procustom-panel-heading">
        <div class="row">
            <div class="col-md-2">
                {% if object.get_prev %}
                    <h2>
                        <a href="{% url 'arche:collection_detail' pk=object.get_prev %}">
                            <i class="fas fa-chevron-left" title="previous"></i>
                        </a>
                    </h2>
                {% endif %}
            </div>
            <div class="col-md-8">
                <h1 style="text-align: center;">
                    <small>collection:</small> {{ object.has_title|truncate_inverse }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'arche:collection_edit' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'arche:collection_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                            <small>
                                <a href="{% url 'arche:resource_inherit' %}?part_of={{ object.id }}">
                                    propragate properties
                                </a>
                            </small>

                    {% endif %}
                </h1>
            </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                        <a href="{% url 'arche:collection_detail' pk=object.get_next %}" style="float:right">
                            <i class="fas fa-chevron-right" title="next"></i>
                        </a>
                    {% endif %}
                </h2>
            </div>
        </div>
    </div>

{% endblock %}

{% block related_objects %}
    <legend>Part Of</legend>
    <a href="{{ object.part_of.get_absolute_url }}">{{ object.part_of }}</a>

    <legend>Children</legend>
    <h4>Collection(s)</h4>
    {% for x in object.has_part.all %}
        <li>
            <a href="{{ x.get_absolute_url }}">{{ x }}</a>
        </li>
    {% endfor %}
    <h4>Resources(s)</h4>
    {% for x in object.has_part_resource.all %}
        <li>
            <a href="{{ x.get_absolute_url }}">{{ x }}</a>
        </li>
    {% endfor %}

{% endblock %}

arche/templates/arche/project_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block title %}Project{% endblock %}
{% block content %}

<div class="container">
    <div class="card procustom-panel-create">
        <div class="card-header procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'arche:project_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>project:</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'arche:project_edit' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'arche:project_delete' pk=object.id %}">
                                   <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'arche:project_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <legend>About</legend>
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            acdh:hasTitle
                        </th>
                        <td>
                            {{ object.has_title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            description
                        </th>
                        <td>
                            {{ object.description }}
                        </td>
                    </tr>
                </table>
                <legend>Related Person</legend>
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            acdh:has_principal
                        </th>
                        <td>
                            {% for x in object.has_principal.all %}
                                <li>
                                    <a href="{{x.get_absolute_url}}">{{ x }}</a>
                                </li>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            acdh:hasContributor(s)
                        </th>
                        <td>
                            {% for x in object.has_contributor.all %}
                                <li>
                                    <a href="{{x.get_absolute_url}}">{{ x }}</a>
                                </li>
                            {% endfor %}
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-6">
                <legend>Related Collection</legend>
                <table class="table table-bordered table-hover">
                    <tr>
                        <td>
                            {% for x in object.related_collection.all %}
                                <a href="{{x.get_absolute_url}}">{{ x }}</a>
                            {% endfor %}
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

arche/templates/arche/repo_object_base.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block title %}Resource{% endblock %}
{% block content %}

<div class="container">
    <div class="card procustom-panel-create">
        {% block repo_header %}
        {% endblock %}
    <div class="card-body">
        <legend>Basic Info</legend>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    acdh:hasTitle
                </th>
                <td>
                    {{ object.has_title }}
                </td>
            </tr>
            <tr>
                <th>
                    acdh:hasIdentifier
                </th>
                <td>
                    {{ object.acdh_id }}
                </td>
            </tr>
            <tr>
                <th>
                    description
                </th>
                <td>
                    {{ object.description }}
                </td>
            </tr>
            <tr>
                <th>
                    checked?
                </th>
                <td>
                    {{ object.checked }}
                </td>
            </tr>
            <tr>
                <th>
                    acdh:hasLicense
                </th>
                <td>
                    {{ object.has_license }}
                </td>
            </tr>
            <tr>
                <th>
                    acdh:hasCategory
                </th>
                <td>
                    <a href="{{ object.has_category }}">{{ object.has_category }}</a>
                </td>
            </tr>
            <tr>
                <th>
                    acdh:hasLifeCycleStatus
                </th>
                <td>
                    <a href="{{ object.has_lcs }}">{{ object.has_lcs }}</a>
                </td>
            </tr>
            <tr>
                <th>
                    acdh:hasAccessRestriction
                </th>
                <td>
                    <a href="{{ object.has_access_restriction }}">{{ object.has_access_restriction }}</a>
                </td>
            </tr>
        </table>
        <legend>Related Person</legend>
        <table class="table table-bordered table-hover">
            {% if object.has_principal.all %}
                <tr>
                    <th>
                        acdh:has_principal
                    </th>
                    <td>
                        {% for x in object.has_principal.all %}
                            <li>
                                <a href="{{x.get_absolute_url}}">{{ x }}</a>
                            </li>
                        {% endfor %}
                    </td>
                </tr>
            {% endif %}
            {% if object.has_creator.all %}
                <tr>
                    <th>
                        acdh:has_creator
                    </th>
                    <td>
                        {% for x in object.has_creator.all %}
                            <li>
                                <a href="{{x.get_absolute_url}}">{{ x }}</a>
                            </li>
                        {% endfor %}
                    </td>
                </tr>
            {% endif %}
            {% if object.has_contributor.all %}
                <tr>
                    <th>
                        acdh:hasContributor(s)
                    </th>
                    <td>
                        {% for x in object.has_contributor.all %}
                            <li>
                                <a href="{{x.get_absolute_url}}">{{ x }}</a>
                            </li>
                        {% endfor %}
                    </td>
                </tr>
            {% endif %}
        </table>
        {% block more_info %}
        {% endblock %}
        {% block related_objects %}
        {% endblock %}

    </div>
    <div class="panel-footer">
        {{ object.label }}
    </div>

</div>
</div>
{% endblock %}

arche/templates/arche/resource_detail.html
{% extends "arche/repo_object_base.html" %}
{% load staticfiles %}
{% block title %}Resource{% endblock %}
{% block repo_header %}


        <div class="card-header procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'arche:resource_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 >
                        <small>resource:</small> {{ object|truncatechars:25 }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'arche:resource_edit' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'arche:resource_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'arche:resource_copy' %}?class-name=arche&id={{ object.id }}&class-name=resource">
                                    <i class="far fa-copy" title="copy object"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'arche:resource_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block more_info %}
    <legend>More Info</legend>
    <table class="table table-bordered table-hover">
        <tr>
            <th>
                acdh:has_filetype
            </th>
            <td>
                {{ object.has_filetype }}
            </td>
        </tr>
        <tr>
            <th>
                acdh:file_size
            </th>
            <td>
                {{ object.file_size }}
            </td>
        </tr>
    </table>
{% endblock %}

{% block related_objects %}
    <legend>Part Of</legend>
    <a href="{{ object.part_of.get_absolute_url }}">{{ object.part_of }}</a>
{% endblock %}